type: intervention_noise_vae
dim_x: ${data.dim_x}
# dim_z: 16
dim_z: 64
overwrite_latents: false

averaging_strategy: stochastic

scm:
  type: mlp
  homoskedastic: false
  adjacency_matrix: none
  manifold_thickness: 0.01
  hidden_units: 100
  hidden_layers: 2
  min_std: 0.2

encoder:
  type: mlp
  flip: false
  # hidden_units: 64
  hidden_units: [6144, 3072, 1536, 768, 384, 192]
  # hidden_layers: 5
  hidden_layers: 5
  std: 0.01
  min_std: 0.0001
  fix_std: false

decoder:
  # hidden_units: 64
  hidden_units: [192, 384, 768, 1536, 3072, 6144, 12288]
  # hidden_layers: 5
  hidden_layers: 10
  std: 1.0
  min_std: 0.001
  fix_std: true

intervention_encoder:
  type: learnable_heuristic
