type: intervention_noise_vae
dim_x: ${data.dim_x}
dim_z: ${data.dim_z}
overwrite_latents: false

averaging_strategy: stochastic

scm:
  type: mlp
  homoskedastic: false
  adjacency_matrix: none
  manifold_thickness: 0.01
  hidden_units: 64
  hidden_layers: 2
  min_std: 0.2

encoder:
  type: mlp
  flip: false
  hidden_units: 64
  hidden_layers: 2
  std: 0.01
  min_std: 0.0001
  fix_std: false

decoder:
  hidden_units: 64
  hidden_layers: 2
  std: 0.1
  min_std: 0.001
  fix_std: false

intervention_encoder:
  type: learnable_heuristic
