batchsize: 64
epochs: 750

clip_grad_norm: 10.0
iwae_samples: 10

full_likelihood: false
likelihood_reduction: sum

early_stopping: false
early_stopping_var: loss

pretrain_epochs: 40
pretrain_beta: 0.001

model_interventions_after_epoch: 250
freeze_encoder_epoch: 1000
deterministic_intervention_encoder_after_epoch: 500
fix_topological_order_epoch: 500

graph_sampling:
  mode: deterministic  # {'deterministic', 'hard', 'soft'}
  temperature: 1.0
  samples: 1

  initial:
    unfreeze_epoch: 0

  final:
    freeze_epoch: 1000
    mode: deterministic
    temperature: 1.0
    samples: 1

lr_schedule:
  type: 'cosine_restarts_reset'
  initial: 0.0008
  minimal: 1.e-8
  restart_every_epochs: 250
  increase_period_by_factor: 1
  step_every_epochs: 0
  step_gamma: 0.1

manifold_thickness_schedule:
  type: 'constant'
  initial: 0.01
  final: 0.01
  initial_constant_epochs: 5
  decay_epochs: 45

beta_schedule:
  type: 'constant_linear_constant'
  initial: 0.0
  final: 3e-5
  initial_constant_epochs: 20
  decay_epochs: 20

increase_intervention_beta: 1.0

z_regularization_schedule:
  type: 'constant_linear_constant'
  initial: 0.01
  final: 0
  initial_constant_epochs: 20
  decay_epochs: 20

edge_regularization_schedule:
  type: 'constant'
  initial: 0
  final: 0
  initial_constant_epochs: 0
  decay_epochs: 0

cyclicity_regularization_schedule:
  type: 'constant'
  initial: 0
  final: 0
  initial_constant_epochs: 0
  decay_epochs: 0

consistency_regularization_schedule:
  type: 'constant'
  initial: 0.01
  final: 0.01
  initial_constant_epochs: 0
  decay_epochs: 0

inverse_consistency_regularization_schedule:
  type: 'constant'
  initial: 0.0
  final: 0.0
  initial_constant_epochs: 0
  decay_epochs: 0

intervention_entropy_regularization_schedule:
  type: 'constant'
  initial: 0.2
  final: 0.2
  initial_constant_epochs: 0
  decay_epochs: 0

intervention_encoder_offset_schedule:
  type: 'constant_exponential_constant'
  initial: 0.025
  final: 1.e-4
  initial_constant_epochs: 20
  decay_epochs: 20

device: 'cuda:1'

log_every_n_steps: 1000
print_every_n_steps: 2000
validate_every_n_steps: 10000
plot_every_n_steps: 100000
save_model_every_n_steps: 10000
